export { ConfirmEmail } from './confirmEmail'
export { ForgotPassword } from './forgotPassword'
export { GeneralInformation } from './generalInfo'
export { Header } from './header'
export { Layout, LayoutSidebar, getLayout, getLayoutSidebar } from './layouts'
export { NewPassword } from './newPassword'
export { NotConfirmEmail } from './notConfirmEmail'
export { PasswordRecoveryExpired } from './passwordRecoveryExpired'
export { PrivacyPolicy } from './privacyPolicy'
export { Profile } from './profile'
export { Public } from './public'
export { SignUp } from './signUp'
export { SignIn } from './singIn'
export { TermOfService } from './termOfService'
